#!/bin/bash
cd src/MonederoBingo/points-configuration-service
title='Points Configuration Service'
echo -n -e "\033]0;$title\007"
sh gradlew clean build -x test
java -jar build/libs/points-configuration-service-0.0.1-SNAPSHOT.jar